name = "BogoMips"
uuid = "9069222b-375b-4282-9f02-7ef1f33c832c"
authors = ["Jacques David <jacques.david@free.fr>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1"
